apiVersion: v1
kind: Namespace
metadata:
  name: weather-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: weather-app:v1  # Eğer Docker Hub'dan çekiyorsan: dockerhubusername/weather-app:tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Minikube'da dışarıdan http://localhost:30080/weather?city=londra ile erişebilirsin
